# Generated by Django 5.0.7 on 2024-07-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='procedure/', verbose_name='изображение')),
                ('price', models.FloatField(verbose_name='цена')),
            ],
            options={
                'verbose_name': 'процедура',
                'verbose_name_plural': 'процедуры',
            },
        ),
    ]
