# Generated by Django 5.0.7 on 2024-07-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='price',
            field=models.IntegerField(verbose_name='цена'),
        ),
    ]
